defaults: &defaults
  password_reset_email_sender: pwd-reset@intersect.org.au
  account_request_user_status_email_sender: account-status@intersect.org.au
  account_request_admin_notification_sender: account-request@intersect.org.au
  batch_files_root: "/data/anznn-uploads"

development:
  <<: *defaults
  batch_files_root: ":rails_root/tmp"

test:
  <<: *defaults
  batch_files_root: ":rails_root/tmp"

production:
  <<: *defaults

staging:
  <<: *defaults

qa:
  <<: *defaults
